name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.2.1
        name: Extract version
        id: extract_version

      - uses: mr-smithers-excellent/docker-build-push@v6.2
        name: Build & Push Docker Image
        with:
          image: deepacks/trade-enjoyer
          tags: ${{ steps.extract_version.outputs.version }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  # pull-update-digital-ocean-swarm:
  #   runs-on: ubuntu-latest
  #   needs: [build-push-docker-image]

  #   steps:
  #     - name: ssh update service
  #       uses: appleboy/ssh-action@v0.1.7
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.KEY }}
  #         passphrase: ${{ secrets.PASSPHRASE }}
  #         script: |
  #           docker image pull deepacks/trade-enjoyer:latest
  #           docker service update --image deepacks/trade-enjoyer:latest --with-registry-auth discord-server
  #           docker container prune -f
  #           docker image prune -f
